"""`legend context` — derived, always-fresh agent context (AGENTS.md), not hand-written.

Human-written AGENTS.md files only help agents for *non-inferable specifics* — the real route
table, the actual module boundaries, the genuine constraints — and go stale the moment code
changes. Legend computes exactly those facts from the code graph, so it can emit them fresh on
every commit. This module renders them as an AGENTS.md (or to stdout).

    legend context                 # print to stdout
    legend context --write AGENTS.md
    legend context --repo path/to/repo -o AGENTS.md
"""
from __future__ import annotations

import datetime as _dt
import os
import sys
from collections import defaultdict
from pathlib import Path

from .config import Config
from .pipeline import build_index
from . import insights, config_map, techdebt


def _area(fid: str) -> str:
    p = fid.replace("\\", "/")
    return p.split("/")[0] if "/" in p else "(root)"


def _architecture(idx):
    areas: dict[str, list[str]] = defaultdict(list)
    deps: dict[str, set[str]] = defaultdict(set)
    for nid, n in idx.graph.nodes.items():
        if n["type"] == "file":
            areas[_area(nid)].append(nid)
    for src, dst, _et in idx.graph.all_edges("imports"):
        a, b = _area(src), _area(dst)
        if a != b:
            deps[a].add(b)
    return areas, deps


def _cross_file_surface(idx, limit: int = 20):
    rows = []
    for nid, n in idx.graph.nodes.items():
        if n["type"] != "symbol":
            continue
        home = n["data"].get("file")
        used_by = sorted({
            idx.graph.get(c)["data"].get("file")
            for c in idx.graph.callers(nid)
            if idx.graph.get(c) and idx.graph.get(c)["type"] == "symbol"
            and idx.graph.get(c)["data"].get("file") != home
        })
        if used_by:
            rows.append((n["data"].get("qualname"), home, used_by))
    rows.sort(key=lambda r: -len(r[2]))
    return rows[:limit]


def _md_table(headers, rows) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(out)


def generate(idx) -> str:
    """Render an AGENTS.md worth of derived facts from a built RepoIndex."""
    s = idx.stats()
    ins = insights.repo_insights(idx)
    langs = insights.language_breakdown(idx)
    routes = insights.api_map(idx)
    models = insights.db_map(idx)
    cfg_surface = config_map.config_surface(idx)
    cycles = techdebt.import_cycles(idx)
    areas, deps = _architecture(idx)
    surface = _cross_file_surface(idx)
    now = _dt.datetime.now().strftime("%Y-%m-%d %H:%M")

    L: list[str] = []
    L.append("# AGENTS.md")
    L.append("")
    L.append(f"> Auto-generated by [Legend](https://pypi.org/project/legend-lens/) "
             f"(`legend context`) from the code graph — **derived facts, not hand-written**, "
             f"so they don't go stale. Regenerate after changes: `legend context --write AGENTS.md`.")
    L.append(f"> Generated {now} at commit `{s.get('commit', '?')}`.")
    L.append("")

    # Project
    lang_str = ", ".join(f"{l['language']} ({l['loc']} LOC)" for l in langs[:6]) or "—"
    L.append("## Project")
    L.append("")
    L.append(f"**{s['repo']}** — {s['files_parsed']} files, {s['symbols']} symbols, "
             f"{ins['loc_total']} LOC, avg complexity {ins['avg_complexity']}. "
             f"Graph: {s['graph_nodes']} nodes / {s['graph_edges']} edges.")
    L.append("")
    L.append(f"Languages: {lang_str}. Python has the deepest analysis (full AST).")
    L.append("")

    # Entry points
    L.append("## Entry points")
    L.append("")
    if ins["entry_files"]:
        for f in ins["entry_files"]:
            L.append(f"- `{f}`")
    else:
        L.append("_No conventional entry points detected (no `__main__` guards or main.py/manage.py/wsgi.py)._")
    L.append("")

    # Architecture
    L.append("## Architecture (areas & dependencies)")
    L.append("")
    L.append("Top-level directories are treated as areas; arrows are real import edges.")
    L.append("")
    for area in sorted(areas):
        d = sorted(deps.get(area, []))
        dep_str = " → depends on: " + ", ".join(d) if d else " (no in-repo deps)"
        L.append(f"- **{area}/** ({len(areas[area])} files){dep_str}")
    L.append("")

    # Routes
    L.append("## HTTP routes")
    L.append("")
    if routes:
        L.append(_md_table(["Method", "Path", "File"],
                           [(r["method"], f"`{r['path']}`", r["file"]) for r in routes[:40]]))
    else:
        L.append("_No HTTP routes detected._")
    L.append("")

    # Models
    L.append("## Data models")
    L.append("")
    if models:
        L.append(_md_table(["Model", "Table", "File"],
                           [(m["model"], m.get("table") or "—", m["file"]) for m in models[:40]]))
    else:
        L.append("_No ORM/data models detected._")
    L.append("")

    # Key files
    L.append("## Key files (most depended-on)")
    L.append("")
    if ins["hub_files"]:
        for h in ins["hub_files"][:10]:
            L.append(f"- `{h['file']}` — imported by {h['imported_by']} file(s)")
    else:
        L.append("_No hub files stand out._")
    L.append("")

    # Public surface
    L.append("## Public surface (symbols used across modules)")
    L.append("")
    if surface:
        for qual, home, used_by in surface:
            L.append(f"- `{qual}` ({home}) — used by {len(used_by)} file(s)")
    else:
        L.append("_No cross-module symbol usage detected._")
    L.append("")

    # Configuration
    if cfg_surface:
        L.append("## Configuration surface")
        L.append("")
        for grp in cfg_surface[:12]:
            items = ", ".join(f"`{i}`" for i in grp.get("items", [])[:20])
            if items:
                L.append(f"- **{grp.get('source', grp.get('kind', 'config'))}**: {items}")
        L.append("")

    # Constraints
    L.append("## Constraints & cautions")
    L.append("")
    if cycles:
        L.append("**Import cycles** (don't deepen these; prefer breaking them):")
        for cyc in cycles[:10]:
            L.append(f"- {' ↔ '.join(cyc)}")
    else:
        L.append("- No import cycles. Keep it that way — run `cycles(base=<branch>)` before merging.")
    if ins["complex_symbols"]:
        L.append("")
        L.append("**High-complexity hotspots** (change carefully, check callers first):")
        for c in ins["complex_symbols"][:5]:
            L.append(f"- `{c['symbol']}` ({c['file']}) — complexity {c['complexity']}")
    L.append("")

    # Agent tips
    L.append("## For coding agents")
    L.append("")
    L.append("This repo can be served by Legend's MCP server for deterministic structure queries "
             "(`uvx --from \"legend-lens[mcp]\" legend mcp --repo .`). Before editing a function call "
             "`blast_radius(symbol)`; before changing a signature call `callers_of(symbol)`; before "
             "merging call `cycles(base=<branch>)`. Paths above are repo-relative.")
    L.append("")
    return "\n".join(L)


def main(argv=None) -> int:
    import argparse
    p = argparse.ArgumentParser(
        prog="legend context",
        description="Emit derived, always-fresh agent context (AGENTS.md) from the code graph.",
    )
    p.add_argument("--repo", default=".", help="repo (or git URL) to analyze (default: current folder)")
    p.add_argument("--write", "-o", dest="write", default=None,
                   help="write to this file (e.g. AGENTS.md); default: print to stdout")
    p.add_argument("--data-dir", default=None, help="index cache dir (default: ~/.legend/cache)")
    args = p.parse_args(argv)

    repo = args.repo
    src_display = repo
    if repo != "." and "://" not in repo:
        repo = str(Path(repo).resolve())
    cfg = Config(
        embed_backend="bm25", llm_provider="", llm_model="",
        data_dir=args.data_dir or os.environ.get("LEGEND_DATA_DIR") or str(Path.home() / ".legend" / "cache"),
    )
    # Progress -> stderr so stdout stays a clean document (supports `legend context > AGENTS.md`).
    idx = build_index(repo, cfg, progress=lambda m: print(m, file=sys.stderr, flush=True), register=False)
    doc = generate(idx)

    if args.write:
        base = Path(repo) if os.path.isdir(repo) else Path.cwd()
        out = Path(args.write)
        if not out.is_absolute():
            out = base / out
        out.write_text(doc, encoding="utf-8")
        print(f"Wrote {out} ({len(doc)} chars) for {src_display}", file=sys.stderr)
    else:
        sys.stdout.write(doc)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
