"""Portable understanding export: a single self-contained HTML page (inline CSS, no external
assets) bundling the overview, insights, per-file explanations, the learning path, and the
mind-map outline — so the understanding Legend built can be shared without running Legend."""
from __future__ import annotations
import html

from .insights import repo_insights, language_breakdown, file_summary
from . import teach
from .media import mindmap_markdown

_CSS = """
body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;max-width:980px;
margin:24px auto;padding:0 18px;color:#1b2a41;line-height:1.5}
h1{color:#1F3864} h2{color:#2E75B6;border-bottom:2px solid #EAF1FB;padding-bottom:4px;margin-top:32px}
.metrics{display:flex;gap:24px;flex-wrap:wrap;margin:12px 0}
.metric{background:#EAF1FB;border-radius:10px;padding:12px 18px;min-width:110px;text-align:center}
.metric .n{font-size:30px;font-weight:700;color:#2E75B6} .metric .l{font-size:12px;color:#555}
details{border:1px solid #e3e9f2;border-radius:8px;padding:8px 12px;margin:8px 0}
summary{cursor:pointer;font-weight:600} code,pre{background:#f5f8fc;border-radius:6px}
pre{padding:12px;overflow:auto} table{border-collapse:collapse;width:100%}
td,th{border:1px solid #e3e9f2;padding:6px 10px;text-align:left;font-size:14px}
.muted{color:#777}
"""


def _esc(x):
    return html.escape(str(x))


def export_html(idx, max_files=40):
    s = idx.stats()
    ins = repo_insights(idx)
    langs = language_breakdown(idx)
    lp = teach.learning_path(idx)
    out = [f"<!doctype html><html><head><meta charset='utf-8'>",
           f"<title>{_esc(s['repo'])} — Understanding</title><style>{_CSS}</style></head><body>",
           f"<h1>{_esc(s['repo'])}</h1>",
           f"<p class='muted'>commit {_esc(s['commit'])} · generated by Legend</p>",
           "<div class='metrics'>",
           f"<div class='metric'><div class='n'>{s['python_files']}</div><div class='l'>code files</div></div>",
           f"<div class='metric'><div class='n'>{s['symbols']}</div><div class='l'>symbols</div></div>",
           f"<div class='metric'><div class='n'>{ins['loc_total']}</div><div class='l'>lines</div></div>",
           f"<div class='metric'><div class='n'>{len(langs)}</div><div class='l'>languages</div></div>",
           "</div>",
           "<h2>Insights</h2><ul>",
           f"<li><b>Entry points:</b> {_esc(', '.join(ins['entry_files']) or '—')}</li>",
           f"<li><b>Hub files:</b> {_esc(', '.join(h['file'] for h in ins['hub_files'][:5]) or '—')}</li>",
           f"<li><b>Most complex:</b> {_esc(', '.join(c['symbol'] for c in ins['complex_symbols'][:5]) or '—')}</li>",
           f"<li><b>Likely unused:</b> {_esc(', '.join(c['symbol'] for c in ins['likely_unused'][:5]) or '—')}</li>",
           "</ul>",
           "<h2>Learning path</h2><ol>"]
    out += [f"<li><b>{_esc(st['file'])}</b> — {_esc(st['why'])}</li>" for st in lp]
    out += ["</ol>", "<h2>Mind map</h2><pre>" + _esc(mindmap_markdown(idx, "__repo__", 3)) + "</pre>",
            "<h2>Files</h2>"]
    shown = 0
    for p in idx.parsed_files:
        if p.language not in ("python", "javascript", "typescript") or shown >= max_files:
            continue
        fs = file_summary(idx, p.file)
        if not fs:
            continue
        shown += 1
        defs = ", ".join(d["symbol"] for d in fs["defines"][:10]) or "—"
        out.append(f"<details><summary>{_esc(p.file)}</summary>"
                   f"<p>{_esc(fs['purpose'] or 'No module docstring.')}</p>"
                   f"<p class='muted'>{fs['loc']} LOC · complexity {fs['complexity_total']} · "
                   f"imports {_esc(', '.join(fs['internal_deps']) or 'none')}</p>"
                   f"<p><b>Defines:</b> {_esc(defs)}</p></details>")
    out.append("</body></html>")
    return "\n".join(out)
