"""Phase 6 — learning media. Auto slide decks (.pptx), a two-host audio overview script
(+ optional TTS), and a Markdown mind-map outline. Deck needs python-pptx; the scripts
and outline are dependency-free. Everything degrades gracefully."""
from __future__ import annotations

from . import teach, techdebt
from .insights import (repo_insights, file_summary, language_breakdown, api_map, db_map)

PALETTE = {"navy": "1F3864", "blue": "2E75B6", "ice": "CADCFC",
           "light": "F4F7FB", "ink": "1B2A41", "white": "FFFFFF", "red": "C0392B"}


# ---------------- deck content (structural) ----------------
def slide_outline(idx, style="technical"):
    s = idx.stats()
    ins = repo_insights(idx)
    langs = language_breakdown(idx)
    lp = teach.learning_path(idx)
    hubs = [h["file"] for h in ins["hub_files"]][:5]
    key_files = []
    for f in (ins["entry_files"][:2] + hubs):
        if f in [k["file"] for k in key_files]:
            continue
        fs = file_summary(idx, f)
        if fs:
            purpose = (fs["purpose"].splitlines()[0] if fs["purpose"] else
                       "defines " + ", ".join(d["symbol"] for d in fs["defines"][:3]))
            key_files.append({"file": f, "purpose": purpose[:90]})
    dead = techdebt.dead_code(idx)
    hots = techdebt.complexity_hotspots(idx)
    dups = techdebt.duplicate_pairs(idx)
    cycles = techdebt.import_cycles(idx)
    undoc = techdebt.undocumented(idx)
    api = api_map(idx)
    db = db_map(idx)

    title = {"type": "title", "title": s["repo"],
             "subtitle": "A guided walkthrough of the codebase",
             "meta": f"commit {s['commit']}  ·  generated by Legend"}
    stats = {"type": "stats", "title": "At a glance",
             "stats": [(str(s["python_files"]), "code files"), (str(s["symbols"]), "symbols"),
                       (str(ins["loc_total"]), "lines"), (str(len(langs)), "languages")]}
    arch = {"type": "bullets", "title": "Architecture at a glance", "bullets": [
        "Entry points: " + (", ".join(ins["entry_files"]) or "—"),
        "Most-connected files: " + (", ".join(hubs) or "—"),
        "Languages: " + ", ".join(f"{l['language']} ({l['files']})" for l in langs),
        f"Code graph: {s['graph_nodes']} nodes, {s['graph_edges']} edges"]}
    comps = {"type": "bullets", "title": "Key components",
             "bullets": [f"{k['file']} — {k['purpose']}" for k in key_files] or ["—"]}
    flow = {"type": "bullets", "title": "Where to start (learning path)",
            "bullets": [f"{i+1}. {st['file']} — {st['why']}" for i, st in enumerate(lp[:6])]}
    cx = {"type": "bullets", "title": "Complexity & hotspots", "bullets": (
        [f"Average complexity per function: {ins['avg_complexity']}"]
        + [f"{h['symbol']} ({h['file']}) — complexity {h['complexity']}" for h in hots[:5]]
        or ["No notable complexity hotspots."])}
    debt = {"type": "bullets", "title": "Technical debt", "bullets": [
        f"Likely-dead code: {len(dead)}" + (" — e.g. " + ", ".join(d['symbol'] for d in dead[:3]) if dead else ""),
        f"Near-duplicate pairs: {len(dups)}",
        f"Import cycles: {len(cycles)}" + (" — " + "; ".join(' ↔ '.join(c) for c in cycles[:2]) if cycles else ""),
        f"Undocumented symbols: {len(undoc)}"]}
    apidb = {"type": "bullets", "title": "API & data", "bullets": (
        [f"{a['method']} {a['path']}  ({a['file']})" for a in api[:6]]
        + [f"model: {m['model']} {('· table ' + m['table']) if m.get('table') else ''} ({m['file']})" for m in db[:5]])
        or None}
    risks = {"type": "bullets", "title": "Risks & recommendations", "bullets": [
        (f"{len(cycles)} import cycle(s) — coupling risk; consider breaking the loop." if cycles else "No import cycles — clean module boundaries."),
        (f"{len(dead)} likely-unused symbol(s) — candidates for removal." if dead else "No obvious dead code."),
        (f"{len(hots)} complexity hotspot(s) — prioritise tests/refactor." if hots else "Complexity is well-distributed."),
        (f"{len(undoc)} undocumented symbol(s) — add docstrings to aid onboarding." if undoc else "Documentation coverage is good.")]}
    close = {"type": "bullets", "title": "Next steps", "bullets": [
        "Open the repo in Legend for the interactive mind map and Q&A.",
        "Follow the learning path, then test yourself in the Learn tab.",
        "Review the flagged tech debt in the Intel tab."]}

    decks = {
        "executive": [title, stats, arch, comps, risks, close],
        "technical": [title, stats, arch, comps, flow, cx, debt] + ([apidb] if apidb["bullets"] else []) + [close],
        "architecture": [title, stats, arch, comps, cx, debt, risks],
    }
    return decks.get(style, decks["technical"])


def build_pptx(idx, style, path):
    """Render the outline to a .pptx. Returns path, or raises if python-pptx is missing."""
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN

    C = {k: RGBColor.from_string(v) for k, v in PALETTE.items()}
    prs = Presentation()
    prs.slide_width, prs.slide_height = Inches(13.333), Inches(7.5)
    blank = prs.slide_layouts[6]

    def bg(slide, color):
        slide.background.fill.solid()
        slide.background.fill.fore_color.rgb = color

    def box(slide, l, t, w, h, text, size, color, bold=False, align=PP_ALIGN.LEFT):
        tb = slide.shapes.add_textbox(Inches(l), Inches(t), Inches(w), Inches(h))
        tf = tb.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.alignment = align
        r = p.add_run()
        r.text = text
        r.font.size, r.font.bold, r.font.color.rgb, r.font.name = Pt(size), bold, color, "Calibri"
        return tb

    def bar(slide, l, t, w, h, color):
        from pptx.enum.shapes import MSO_SHAPE
        sh = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(l), Inches(t), Inches(w), Inches(h))
        sh.fill.solid(); sh.fill.fore_color.rgb = color; sh.line.fill.background()
        return sh

    for spec in slide_outline(idx, style):
        sl = prs.slides.add_slide(blank)
        if spec["type"] == "title":
            bg(sl, C["navy"])
            bar(sl, 0.9, 3.5, 2.2, 0.08, C["blue"])
            box(sl, 0.9, 2.3, 11.5, 1.3, spec["title"], 44, C["white"], bold=True)
            box(sl, 0.9, 3.7, 11.5, 0.8, spec["subtitle"], 22, C["ice"])
            box(sl, 0.9, 6.6, 11.5, 0.5, spec["meta"], 12, C["ice"])
        elif spec["type"] == "stats":
            bg(sl, C["light"])
            bar(sl, 0.0, 0.0, 13.333, 0.18, C["blue"])
            box(sl, 0.9, 0.5, 11.5, 0.9, spec["title"], 30, C["navy"], bold=True)
            n = len(spec["stats"]) or 1
            w = 11.5 / n
            for i, (num, lab) in enumerate(spec["stats"]):
                x = 0.9 + i * w
                box(sl, x, 2.6, w, 1.4, num, 60, C["blue"], bold=True, align=PP_ALIGN.CENTER)
                box(sl, x, 4.1, w, 0.6, lab, 16, C["ink"], align=PP_ALIGN.CENTER)
        else:  # bullets
            bg(sl, C["light"])
            bar(sl, 0.0, 0.0, 13.333, 0.18, C["blue"])
            box(sl, 0.9, 0.5, 11.5, 0.9, spec["title"], 30, C["navy"], bold=True)
            tb = sl.shapes.add_textbox(Inches(0.9), Inches(1.7), Inches(11.5), Inches(5.2))
            tf = tb.text_frame
            tf.word_wrap = True
            for i, b in enumerate(spec["bullets"] or ["—"]):
                p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
                p.space_after = Pt(10)
                r = p.add_run()
                r.text = "•  " + str(b)
                r.font.size, r.font.color.rgb, r.font.name = Pt(18), C["ink"], "Calibri"
    prs.save(path)
    return path


# ---------------- audio overview (two-host dialogue) ----------------
def audio_script(idx, model="", extra=None):
    s = idx.stats()
    ins = repo_insights(idx)
    lp = teach.learning_path(idx)
    hubs = ", ".join(h["file"] for h in ins["hub_files"][:3]) or "the core modules"
    hots = techdebt.complexity_hotspots(idx)
    dead = techdebt.dead_code(idx)
    entries = ", ".join(ins["entry_files"]) or "its main module"
    facts = (f"repo={s['repo']}, files={s['python_files']}, symbols={s['symbols']}, "
             f"entry points={ins['entry_files']}, hubs={[h['file'] for h in ins['hub_files'][:3]]}, "
             f"avg_complexity={ins['avg_complexity']}, hotspots={[h['symbol'] for h in hots[:3]]}, "
             f"likely_unused={[d['symbol'] for d in dead[:3]]}, "
             f"learning_path={[st['file'] for st in lp[:5]]}")

    if model:
        try:
            from . import llm
            prompt = ("Write a friendly ~10-turn podcast dialogue between two hosts, MAYA "
                      "(curious host) and DEV (engineer), explaining this codebase to a new "
                      "engineer. Cover what it is, how it's structured, the main flow, and any "
                      "risks. Use the facts; do not invent specifics. Format each line as "
                      "'MAYA: ...' or 'DEV: ...'.\n\nFacts: " + facts)
            r = llm._complete(model, [
                {"role": "system", "content": "You write engaging, accurate technical podcasts."},
                {"role": "user", "content": prompt}], extra=extra, temperature=0.5, timeout=90)
            text = r["choices"][0]["message"]["content"].strip()
            out = []
            for line in text.splitlines():
                line = line.strip()
                for sp in ("MAYA", "DEV"):
                    if line.upper().startswith(sp + ":"):
                        out.append({"speaker": sp.title(), "text": line.split(":", 1)[1].strip()})
                        break
            if out:
                return out
        except Exception:
            pass

    # structural fallback
    return [
        {"speaker": "Maya", "text": f"Welcome! Today we're walking through {s['repo']} — about {s['python_files']} files and {s['symbols']} symbols. Dev, where does it begin?"},
        {"speaker": "Dev", "text": f"Execution starts at {entries}. From there the work flows through the core modules."},
        {"speaker": "Maya", "text": "Which files matter most if I'm new here?"},
        {"speaker": "Dev", "text": f"The most-connected files are {hubs} — understanding those gives you most of the system."},
        {"speaker": "Maya", "text": "How would I actually learn it?"},
        {"speaker": "Dev", "text": "Start with the entry points, then the hubs, then the periphery — " + ("; ".join(st["file"] for st in lp[:4]) + ".")},
        {"speaker": "Maya", "text": "Anything complex or risky to watch for?"},
        {"speaker": "Dev", "text": (("The most complex piece is " + hots[0]["symbol"] + f" (complexity {hots[0]['complexity']}). ") if hots else "Complexity is well-distributed. ") + (("There are also " + str(len(dead)) + " likely-unused symbols worth a look.") if dead else "And little obvious dead code.")},
        {"speaker": "Maya", "text": "Great overview. So newcomers should start at the entry points and follow the learning path?"},
        {"speaker": "Dev", "text": "Exactly — and use Legend's mind map and quizzes to lock it in. Thanks for listening!"},
    ]


def script_to_text(script):
    return "\n\n".join(f"{t['speaker']}: {t['text']}" for t in script)


def synthesize_audio(script, out_path, voice_a="en-US-AriaNeural", voice_b="en-US-GuyNeural"):
    """Best-effort TTS. Tries edge-tts (multi-voice), then pyttsx3, then gTTS. Returns
    (path|None, message). None of these are required; the script is the primary artifact."""
    text = script_to_text(script)
    # edge-tts (multi-voice, async)
    try:
        import asyncio
        import edge_tts

        async def _run():
            import io
            from pydub import AudioSegment  # noqa
            seg = None
            for t in script:
                voice = voice_a if t["speaker"].lower().startswith("m") else voice_b
                comm = edge_tts.Communicate(t["text"], voice)
                tmp = out_path + f".{id(t)}.mp3"
                await comm.save(tmp)
                a = AudioSegment.from_file(tmp)
                seg = a if seg is None else seg + a
            seg.export(out_path, format="mp3")
        asyncio.run(_run())
        return (out_path, "edge-tts (two voices)")
    except Exception:
        pass
    try:
        import pyttsx3
        eng = pyttsx3.init()
        eng.save_to_file(text, out_path)
        eng.runAndWait()
        return (out_path, "pyttsx3 (single voice)")
    except Exception:
        pass
    try:
        from gtts import gTTS
        gTTS(text).save(out_path)
        return (out_path, "gTTS (single voice, online)")
    except Exception as e:
        return (None, f"No TTS backend available ({type(e).__name__}). "
                      "Install edge-tts (+pydub) or pyttsx3 for audio export; "
                      "the transcript above is ready to read or feed to any TTS.")


# ---------------- markdown mind-map outline ----------------
def mindmap_markdown(idx, root="__repo__", depth=3, etypes=("contains", "calls"), max_children=8):
    from .diagram import mindmap_tree
    g = idx.graph
    nodes, tree = mindmap_tree(idx, root, depth, etypes, max_children)
    kids = {}
    for a, b in tree:
        kids.setdefault(a, []).append(b)

    def label(n):
        if n == "__repo__":
            return idx.meta.name + " (repo)"
        nd = g.get(n)
        return (nd["data"].get("qualname") or n) if nd else n

    lines = []

    def walk(n, d):
        lines.append("  " * d + "- " + label(n))
        for c in kids.get(n, []):
            walk(c, d + 1)
    walk(root, 0)
    return "\n".join(lines)
