import { useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { kycApi, AskResponse } from '../../api/client';
import './Ask.css';

export default function Ask() {
  const { repoId } = useParams<{ repoId: string }>();
  const [q, setQ] = useState('How does the inference flow work?');
  const [asking, setAsking] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<AskResponse | null>(null);

  const ask = async () => {
    if (!repoId || !q.trim()) return;
    setAsking(true); setError(null);
    try {
      const r = await kycApi.ask(repoId, q.trim());
      setResult(r.data);
    } catch (e: any) {
      setError(e?.response?.data?.detail || 'Ask failed');
    } finally {
      setAsking(false);
    }
  };

  return (
    <div>
      <div className="page-header">
        <h1>Ask the codebase</h1>
        <p>Ask anything about the indexed repo. Answers are generated by your configured model, with sources cited inline.</p>
      </div>

      <div className="card">
        <div className="ask__row">
          <input
            className="input"
            value={q}
            onChange={e => setQ(e.target.value)}
            onKeyDown={e => { if (e.key === 'Enter' && !asking) ask(); }}
            placeholder="What does this repo do? How does X work? Where is Y defined?"
            disabled={asking}
            autoFocus
          />
          <button className="btn btn--primary" onClick={ask} disabled={asking || !q.trim()}>
            {asking ? 'Asking…' : 'Ask'}
          </button>
        </div>
        {error && <div className="toast toast--err" style={{ marginTop: 12 }}>{error}</div>}
      </div>

      {asking && <div className="dash-loading">Retrieving and synthesizing…</div>}

      {result && !asking && (
        <>
          {result.used_llm && result.answer && (
            <div className="card">
              <div className="card-header"><h3>Answer</h3></div>
              <div className="ask__answer">{result.answer}</div>
            </div>
          )}
          {!result.used_llm && (
            <div className="card">
              <div className="toast toast--err">
                <strong>Answers need a model.</strong> {result.reason || 'Connect a local Ollama model or a provider key, then ask again.'}{' '}
                <Link to="/settings" style={{ color: 'var(--kyc-accent)', fontWeight: 600 }}>Open AI settings</Link>.
              </div>
            </div>
          )}

          {result.used_llm && (
          <div className="card">
            <div className="card-header">
              <h3>Sources ({result.sources.length})</h3>
            </div>
            {result.sources.length === 0 ? (
              <p className="ov-muted">— no sources retrieved —</p>
            ) : (
              <div className="ask__sources">
                {result.sources.map((s, i) => (
                  <details key={i} className="ask__source">
                    <summary className="ask__source-head">
                      <span className="ask__source-file">
                        <code>{s.file}</code>:{s.start_line}-{s.end_line}
                      </span>
                      <span className="ask__source-name"><code>{s.name}</code></span>
                      <span className="ask__source-meta">
                        <span className={`ask__source-via ask__source-via--${s.via}`}>{s.via}</span>
                        <span className="ask__source-score">score {s.score.toFixed(3)}</span>
                      </span>
                    </summary>
                    <pre className="ask__source-code">{s.text}</pre>
                  </details>
                ))}
              </div>
            )}
          </div>
          )}
        </>
      )}
    </div>
  );
}
